MAIN_WINDOW_BG_COLOR = "#BCFFBD"
BTN_RUN_MAIN_BG_COLOR ="#A8E6A2"
BTN_RUN_MAIN_HOVER_COLOR = "#90D890"

NO_DETECTED_CAMERA_NAME = '카메라가 검색되지 않음'

SIGNAL_NO_DETECTED_CAMERA = 'NO_DETECTED_CAMERA'
SIGNAL_NO_SEARCHED_CAMERA = 'NO_SEARCHED_CAMERA'
